name: my-docker-project


services:
  app:
    build: .
    image: django-starter-image
    container_name: django-starter-container
    command: /app/entrypoint.sh
    ports:
      - "8008:8008"
    volumes:
      - .:/app
    env_file:
      - ./a_core/.env    
    depends_on:
      - postgres  
      - redis 
    restart: unless-stopped


  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    restart: unless-stopped  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  
  celery:
    image : django-starter-image 
    container_name: my-celery-container
    command: celery -A a_core worker -E -l info
    volumes:
      - .:/app
    env_file:
      - ./a_core/.env      
    depends_on:
      - postgres
      - redis
      - app  


  flower:
    image : django-starter-image
    container_name: my-flower-container
    command: celery -A a_core flower --basic_auth=admin:password123 
    ports:
      - "5555:5555"
    depends_on:
      - redis
    env_file:
      - ./a_core/.env      


  beat:
    image: django-starter-image
    container_name: my-beat-container
    command: celery -A a_core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - ./a_core/.env      
    depends_on:
      - redis
      - app    

volumes:
  postgres_data:
  redis_data:

