name: Publish Docker Images

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Build and Publish Docker Images
        run: |
          docker login ghcr.io --username abrs7 --password ${{secrets.MY_PAT}}
          docker build -t ghcr.io/abrs7/django-docker-new
          docker push ghcr.io/abrs7/django-docker-new